name: Build and Deploy

on:
  pull_request:

  # on:
  #   push:
  #     branches:
  #       - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create production env file
        run: |
          touch .env

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Deploy 🚀
        run: npm run build

      # - name: Prepare for staging deployment
      #   # if: ${{ vars.IS_STAGING == 'true' }}
      #   run: |
      #     echo "docs.paranode.io" > out/CNAME
      #     echo "User-Agent: *" > out/robots.txt
      #     echo "Disallow: /" >> out/robots.txt

      - name: Deploy 🚀
        uses: jamesives/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: github-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
